### PR TITLE
Use fixed version of Vert.x and MySQL PostgreSQL client

### PR DESCRIPTION
**Pull request by Narigo**
I use two variables now, to be able to fix problems with mysql postgresql client directly if needed.

### CODE REVIEW

**Comment by alexvetter** [comment]
lol

**Comment by alexvetter** [comment]
Can be merged, the failed test has nothing to do with the PR. It's legacy timeout handling stuff which I should have removed already... (sorry).

```
 SEVERE: Database (commit) action failed.
    java.util.concurrent.TimeoutException: Operation timed out after 1000 millis
```

**Comment by Narigo** [comment]
I've merged it now. Thanks for fixing it ;)

**Comment by alexvetter** [comment]
pffff

**Pull request merged**
